service: lighthouse-server
frameworkVersion: "3"


provider:
  name: aws
  runtime: nodejs16.x


functions:
  server:
    handler: index.handler
    events:
      - httpApi:
          path: '*'
          method: '*'
    environment:
      DB_URL: ${param:db_url}