name: CI

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: Set env var
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV

      - name: Deploy serverless app
        run: npm run deploy
